#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <time.h>

int circle_points = 0;
int total_points;
pthread_mutex_t mutex;		//Use mutex to prevent race conditions among threads. 

//This function checks if the points are located insed the circle.
int pointscheck(double x , double y){
	return (x*x +y*y) <=1;
}

void* generatepoints(void* args){
	int pcirc = 0;		//Points in the circle.

	srand(time(NULL));	//This seeds the random number generator.

	for(int i=0; i<total_points; i++){			//Loop throught the total number of points.
		double x =(double)rand()/ RAND_MAX*2.0 -1.0;	//For each point in x and y between -1 and 1 are generated by scaling rand, which is a value that returned between 0 and RAND MAX.
		double y = (double)rand()/RAND_MAX*2.0-1.0;

		if(pointscheck(x, y)){		//Call the points check function to check if the points are within the circle.
			pcirc++;
		}
	}
	pthread_mutex_lock(&mutex);		//After iterating through the thread is locked so that the global circle points can be updated.
	circle_points += pcirc;
	pthread_mutex_unlock(&mutex);		//Unclock after the update has been completed.

	pthread_exit(0);			//Exit the thread.
}

int main(int argc, char *argv[]){
	if(argc != 3){			//Check if the user has placed two command-line arguements. 
		fprintf(stderr, "Usage: %s <number of points> <number of threads>\n", argv[0]);
		return 1;
	}
	total_points = atoi(argv[1]);			//Convert the string arguments into integers and placed them into the variables.
	int num_threads = atoi(argv[2]);

	pthread_t thread[num_threads];			//This is an array of threads with the size provided by the user.
	pthread_mutex_init(&mutex, NULL);		//Initialize the mutex.

	for(int i=0; i<num_threads; i++){					//Create a threads equal to the total amount of entered threads.
		pthread_create(&thread[i], NULL, generatepoints, NULL);
	}

	for(int i=0; i<num_threads; i++){					//Wait for all the threads to be completed.
		pthread_join(thread[i], NULL);
	}
	//Calculate and display the appoximation of pi.
	double pi_est = 4.0 * circle_points/ (total_points*num_threads);
	printf("Estimated value for pi = %.4f\n", pi_est);

	pthread_mutex_destroy(&mutex);		//Empty all the resources allocated for the mutext.
	return 0; 
}
